stages:
  - build
  - deploy

build_docker_image:
  stage: .pre
  image: docker:27
  services:
    - docker:27-dind
  script:
    - docker version
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build --platform linux/arm64 -t $CI_REGISTRY_IMAGE/myapp2 -f ci/Dockerfile .
    - docker image ls
    - docker push $CI_REGISTRY_IMAGE/myapp2
